#ifndef CNBIDRAW_FLAGS_HPP
#define CNBIDRAW_FLAGS_HPP


#define CNBIDRAW_WINDOW_DEFAULT_CAPTION 	"Cnbi Window"
#define CNBIDRAW_WINDOW_DEFAULT_WIDTH		800
#define CNBIDRAW_WINDOW_DEFAULT_HEIGHT		600
#define CNBIDRAW_WINDOW_DEFAULT_X			0
#define CNBIDRAW_WINDOW_DEFAULT_Y			0
#define CNBIDRAW_WINDOW_DEFAULT_BPP 		24

#define CNBIDRAW_ENGINE_DEFAULT_REFRESH 	50.0f 	// [Hz]

#define CNBIDRAW_SHAPE_DEFAULT_X			0.0f
#define CNBIDRAW_SHAPE_DEFAULT_Y			0.0f
#define CNBIDRAW_SHAPE_DEFAULT_FILLED		1
#define CNBIDRAW_SHAPE_DEFAULT_NPOINTS		100

#define CNBIDRAW_ARROW_DEFAULT_THICK		0.5f // [%]
#define CNBIDRAW_ARROW_DEFAULT_SQUEEZE		0.3f // [%]

#define CNBIDRAW_IMAGE_DEFAULT_MXLVL		4

#define CNBIDRAW_STRING_DEFAULT_FORMAT		"arial:style=bold italic"
#define CNBIDRAW_STRING_DEFAULT_ALIGN		DTK_HMID|DTK_VMID

#endif
